AWSTemplateFormatVersion: "2010-09-09"
Description: Simple cloud formation for bucket creation and configuration

Parameters:
  BucketName: { Type: String, Default: "bucket-with-cloudformation-1" }
  IAMUserName:
    Type: String
    Description: IAM User Name
    Default: "user1"
    ConstraintDescription: must be a valid IAM user name

Resources:  
  AccessLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      Tags:
      - Key: 'iac-type'
        Value: 's3'
        AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    a362be33-b009-4a82-a31a-3d58d013e3cf:
      size:
        width: 60
        height: 60
      position:
        x: 414
        'y': 176
      z: 0
    598902f5-e815-4438-8cc9-b9ab132245f1:
      size:
        width: 140
        height: 140
      position:
        x: 600
        'y': 169
      z: 0
Resources:
  EC2I1HVIG:
    Type: 'AWS::EC2::Instance'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a362be33-b009-4a82-a31a-3d58d013e3cf
  EC2VPC3VDDS:
    Type: 'AWS::EC2::VPC'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 598902f5-e815-4438-8cc9-b9ab132245f1

#   VPC:
#     Type: AWS::EC2::VPC
#     Properties:
#       CidrBlock: 10.1.0.0/16
#       EnableDnsSupport: true
#       EnableDnsHostnames: true
#       Tags:
#       - Key: 'iac-type'
#         Value: 'vpc'

#   taskdefinition:
#     Type: 'AWS::ECS::TaskDefinition'
#     DeletionPolicy : Retain
#     Properties:
#       containerDefinitions:
#         - command:
#             - >-
#               /bin/sh -c "echo '<html> <head> <title>Amazon ECS Sample
#               App</title> <style>body {margin-top: 40px; background-color:
#               #333;} </style> </head><body> <div
#               style=color:white;text-align:center> <h1>Amazon ECS Sample
#               App</h1> <h2>Congratulations!</h2> <p>Your application is now
#               running on a container in Amazon ECS.</p> </div></body></html>' > 
#               /usr/local/apache2/htdocs/index.html && httpd-foreground"
#           entryPoint:
#             - sh
#             - '-c'
#           essential: true
#           image: 'httpd:2.4'
#           logConfiguration:
#             logDriver: awslogs
#             options:
#               awslogs-group: /ecs/fargate-task-definition
#               awslogs-region: us-east-1
#               awslogs-stream-prefix: ecs
#           name: sample-fargate-app
#           portMappings:
#             - containerPort: 80
#               hostPort: 80
#               protocol: tcp
#       cpu: '256'
#       executionRoleArn: 'arn:aws:iam::978526189023:role/ecs_cloudf'
#       family: fargate-task-definition-cfn
#       memory: '512'
#       networkMode: awsvpc
#       requiresCompatibilities:
#         - FARGATE
#       runtimePlatform:
#         OperatingSystemFamily: LINUX     
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    7c791609-0a54-46f9-9dd1-b69e8cc781e7:
      size:
        width: 60
        height: 60
      position:
        x: 446
        'y': 117
      z: 0
    18e57266-58d5-4e58-ad7b-35c2bda94b74:
      size:
        width: 60
        height: 60
      position:
        x: 624
        'y': 135
      z: 0
Resources:
  ECRR4Z8GH:
    Type: 'AWS::ECR::Repository'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7c791609-0a54-46f9-9dd1-b69e8cc781e7
  ECSC4A7XB:
    Type: 'AWS::ECS::Cluster'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 18e57266-58d5-4e58-ad7b-35c2bda94b74

