AWSTemplateFormatVersion: "2010-09-09"
Description: Simple cloud formation for bucket creation and configuration

Parameters:
  BucketName: { Type: String, Default: "bucket-with-cloudformation-1" }
  IAMUserName:
    Type: String
    Description: IAM User Name
    Default: "user1"
    ConstraintDescription: must be a valid IAM user name

Resources:  
  AccessLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      Tags:
      - Key: 'iac-type'
        Value: 's3'

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: 'iac-type'
        Value: 'vpc'



          



